### ISSUE TITLE
TypeError: descriptor '__init__' requires a 'super' object but received a 'str'        

### ISSUE THREAD

**Issue by mstram** [s390guy/SATK#2]
```
*           xmode psw,ec
begin      start  0
L1234567   CSECT
        lr  1,1
*
        dc x'01'
       END
```

---

Traceback (most recent call last):  
  File "/home/action/git/SATK/asma/asminput.py", line 184, in init  
    self.fname,self.fo=pathmgr.ropen(self.rname)  
  File "/home/action/git/SATK/tools/satkutil.py", line 533, in ropen  
    % (mode,filename)) from None  
ValueError: could not open in mode 'rt' path: /home/action/git/SATK/mike/c1                                                                    

During handling of the above exception, another exception occurred:                                                                            

Traceback (most recent call last):  
  File "/home/action/git/SATK/tools/asma.py", line 256, in <module>  
    ASMA(args,dm).run()  
  File "/home/action/git/SATK/tools/asma.py", line 95, in run  
    self.assembler.statement(filename=self.source)  
  File "/home/action/git/SATK/asma/assembler.py", line 4488, in statement  
    self.LB.newFile(filename)  
  File "/home/action/git/SATK/asma/asminput.py", line 470, in newFile  
    self.**source("F",fname,stmtno=stmtno,srcno=self._fileno)  
  File "/home/action/git/SATK/asma/asminput.py", line 411, in __source  
    srco.init(pathmgr=self._opath)  
  File "/home/action/git/SATK/asma/asminput.py", line 186, in init  
    raise SourceError("could not open for reading text file: %s" % self.fname) \  
  File "/home/action/git/SATK/asma/asminput.py", line 60, in __init**  
    super.**init**(msg)  
TypeError: descriptor '**init**' requires a 'super' object but received a 'str'

**Comment by Fish-Git** [comment]
FYI: Shouldn't this issue be closed?
