### ISSUE TITLE
dc 'd'

### ISSUE THREAD

**Issue by mstram** [s390guy/SATK#3]
```
      xmode psw,ec
begin      start  0
L1234567   CSECT
*
            DC  d'42' 
            DC  D'42'
*num1       dc  D'42'
*num2       dc  d'42'
```

---

asma.py Copyright (C) 2014 Harold Grovesteen  
P[5:17]-0 'dc_stmt' error  encountered: 'd'  
Traceback (most recent call last):  
  File "/home/action/git/SATK/tools/asma.py", line 256, in <module>  
    ASMA(args,dm).run()  
  File "/home/action/git/SATK/tools/asma.py", line 95, in run  
    self.assembler.statement(filename=self.source)  
  File "/home/action/git/SATK/asma/assembler.py", line 4538, in statement  
    self.__pre_process(s,debug=sdebug)  
  File "/home/action/git/SATK/asma/assembler.py", line 2905, in __pre_process  
    self.__parse(s)  
  File "/home/action/git/SATK/asma/assembler.py", line 2799, in __parse  
    self.__error(eo.print(string=True))  
  File "/home/action/git/SATK/asma/assembler.py", line 1985, in __error  
    raise ValueError("%s\nassembler terminated" % string) from None  
ValueError: P[5:17]-0 'dc_stmt' error  encountered: 'd'  
assembler terminated  
           END

**Comment by Fish-Git** [comment]
FYI: shouldn't this issue be closed? Lower case 'd' works fine for me!
