### ISSUE TITLE
START  0 (zero) not accepted

### ISSUE THREAD

**Issue by mstram** [s390guy/SATK#4]
```
           XMODE PSW,EC
BEGIN      START  0
D101A      CSECT
           END
```
# 

Traceback (most recent call last):  
  File "/home/action/git/SATK/tools/asma.py", line 268, in <module>  
    ASMA(args,dm).run()  
  File "/home/action/git/SATK/tools/asma.py", line 102, in run  
    self.assembler.assemble()  
  File "/home/action/git/SATK/asma/assembler.py", line 4567, in assemble  
    method(s,trace=pdebug)  
  File "/home/action/git/SATK/asma/assembler.py", line 4415, in _region_pass2  
    addr2=addr1+(len(region)-1)  
  File "/home/action/git/SATK/asma/assembler.py", line 5150, in __add__  
    self.address+other,self,"+",other,rsup=rsup)  
  File "/home/action/git/SATK/asma/assembler.py", line 4972, in _ck  
    % (a,op,b,v))  
assembler.AddrArithError: negative address not supported ABS:0x0 + -1: -1

**Comment by Fish-Git** [comment]
FYI: shouldn't this issue be closed now? Mike's code works fine for me!
